<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { MoreHorizontal, Plus, Star, Trash2, RotateCcw } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'; import ProjectModal from '../components/ProjectModal.vue'; import { useProjectStore } from '../stores/projectStore'
const store = useProjectStore(); const route = useRoute(); const router = useRouter(); const search = ref(''); const showModal = ref(false)
onMounted(() => { if (!store.ready) store.hydrate() })
const filter = computed(() => String(route.query.filter ?? 'all')); const projects = computed(() => store.projects.filter((project) => { const match = project.name.toLowerCase().includes(search.value.toLowerCase()); return match && (filter.value === 'favorites' ? project.favorite && !project.deletedAt : filter.value === 'trash' ? !!project.deletedAt : !project.deletedAt) }))
const title = computed(() => filter.value === 'favorites' ? 'Favorites' : filter.value === 'trash' ? 'Trash' : 'My projects')
function open(id: string) { router.push(`/project/${id}`) }
</script>
<template><AppShell><section class="dashboard"><header class="view-header"><div><p class="eyebrow">WORKSPACE</p><h1>{{ title }}</h1><p class="muted">Organize and bring your ideas to life.</p></div><button class="button primary" @click="showModal=true"><Plus :size="18"/>New project</button></header><input v-model="search" class="search" placeholder="Search projects..."><div v-if="projects.length" class="project-grid"><article v-for="project in projects" :key="project.id" class="project-card" @click="open(project.id)"><div class="thumbnail"><div class="mini-device" :class="project.deviceType"><span></span><span></span><span></span></div></div><div class="card-content"><div><h3>{{ project.name }}</h3><p>{{ store.screens.filter((screen) => screen.projectId === project.id).length }} screens · Edited {{ new Date(project.updatedAt).toLocaleDateString() }}</p></div><div class="card-actions" @click.stop><button :aria-label="project.favorite ? 'Remove favorite' : 'Favorite'" @click="store.toggleFavorite(project)"><Star :size="17" :fill="project.favorite ? 'currentColor' : 'none'"/></button><button v-if="filter !== 'trash'" aria-label="Move to trash" @click="store.trashProject(project)"><Trash2 :size="17"/></button><button v-else aria-label="Restore project" @click="store.restoreProject(project)"><RotateCcw :size="17"/></button><button v-if="filter === 'trash'" aria-label="Delete permanently" @click="store.deleteProject(project)"><MoreHorizontal :size="17"/></button></div></div></article></div><div v-else class="empty"><h2>{{ filter === 'trash' ? 'Nothing in trash' : 'Your next idea starts here.' }}</h2><p class="muted">Create a project to begin sketching your interface.</p><button v-if="filter !== 'trash'" class="button primary" @click="showModal=true">Create project</button></div></section><ProjectModal v-model="showModal" /></AppShell></template>
