<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, Plus } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'; import { useProjectStore } from '../stores/projectStore'; import type { DeviceType } from '../types'
const store = useProjectStore(); const route = useRoute(); const router = useRouter(); const showCreate = ref(false); const name = ref('New screen'); const device = ref<DeviceType>('iphone')
onMounted(() => { if (!store.ready) store.hydrate() }); const project = computed(() => store.projects.find((item) => item.id === route.params.id)); const screens = computed(() => store.screens.filter((item) => item.projectId === route.params.id))
async function createScreen() { const screen = await store.createScreen(String(route.params.id), name.value || 'Untitled screen', device.value); showCreate.value = false; router.push(`/project/${route.params.id}/screen/${screen.id}`) }
</script>
<template><AppShell><section v-if="project" class="project-view"><RouterLink class="back" to="/"><ArrowLeft :size="17"/>All projects</RouterLink><header class="view-header"><div><p class="eyebrow">PROJECT</p><h1>{{ project.name }}</h1><p class="muted">{{ project.description || 'A collection of interface ideas.' }}</p></div><button class="button primary" @click="showCreate=true"><Plus :size="18"/>New screen</button></header><div class="screen-grid"><button v-for="screen in screens" :key="screen.id" class="screen-card" @click="router.push(`/project/${project.id}/screen/${screen.id}`)"><div class="screen-thumb"><div :class="['screen-frame', screen.deviceType]"> <span></span><span></span><span></span></div></div><div><h3>{{ screen.name }}</h3><p>{{ screen.width }} × {{ screen.height }}</p></div></button><button class="screen-card add-screen" @click="showCreate=true"><Plus :size="24"/><span>Add a screen</span></button></div></section><Teleport to="body"><div v-if="showCreate" class="modal-backdrop" @mousedown.self="showCreate=false"><form class="modal small" @submit.prevent="createScreen"><p class="eyebrow">NEW SCREEN</p><h2>Choose your canvas.</h2><label>Screen name<input v-model="name"></label><div class="device-options"><button v-for="item in ([['iphone','iPhone'],['android','Android'],['desktop','Desktop'],['tablet','Tablet']] as [DeviceType,string][])" :key="item[0]" type="button" :class="{chosen:device===item[0]}" @click="device=item[0]">{{ item[1] }}</button></div><div class="modal-actions"><button type="button" class="button ghost" @click="showCreate=false">Cancel</button><button class="button primary">Create screen</button></div></form></div></Teleport></AppShell></template>
